# Generated by Django 3.0.7 on 2021-11-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='discounts',
        ),
    ]
